### ISSUE TITLE
Error message 'Empty reply from server' when executing CURL command

### ISSUE THREAD

**Issue by slimline33** [felixcrafter54/message-client#1]
Hi!

I'm trying to send messages to message-client over curl.

When executing the following CURL command:

`
curl -vX POST http://192.168.1.12:8080/ -H "Authorization: Basic YWRtaW46MTIzNDU=" -d '{"type":"message","payload":"Hello, this is a test message!"}'
`

I receive the following error message:

```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.1.12:8080...
* Connected to 192.168.1.12 (192.168.1.12) port 8080
> POST / HTTP/1.1
> Host: 192.168.1.12:8080
> User-Agent: curl/8.4.0
> Accept: */*
> Authorization: Basic YWRtaW46MTIzNDU
> Content-Length: 51
> Content-Type: application/x-www-form-urlencoded
>
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

Please can you assist me in diagnosing and resolving this issue. 

Thank you in advance for your support!

**Comment by SternduCode** [comment]
What version are you using? @slimline33

**Comment by slimline33** [comment]
@SternduCode 

v1.4 Latest on Aug 25, 2023

**Comment by SternduCode** [comment]
Ok i dont have this issue, if i send the curl request from the same device that the messageclient is running from
@slimline33

**Comment by SternduCode** [comment]
Can you validate the messageclient is running on the device and there are no other apps running on port 8080? @slimline33

**Comment by slimline33** [comment]
![image](https://github.com/felixcrafter54/message-client/assets/3323812/302b3d02-2570-4935-b440-7de33331b485)

The tip with the same machine was valuable. I was trying that locally via cmd the whole time, and there I got the error 'Empty Reply'...

Now I tried it via SSH from the ioBroker server, and lo and behold, it works so far.

**Comment by SternduCode** [comment]
huh, thats weird. The curl from CMD for some reason doesnt work... fascinating

**Comment by slimline33** [comment]
yes really weird. A change to localhost also without funktion.

But now it run! But not 100% smoothly yet. While some hotkeys are being passed through, not all of them are. I can send CTRL+SHIFT+P and it brings up the print screen program, but I can't lock Windows with WIN+L. Then Message-Client will write the Letter itself. I think I will add a new issue to implement shutdown/lock/standby/reboot

**Comment by SternduCode** [comment]
![debug](https://github.com/felixcrafter54/message-client/assets/57641750/b853912c-a23b-4af3-9c7b-c652ae9e5846)

I dont understand what is different...

**Comment by slimline33** [comment]
seems different curls on windows and linux?

**Comment by SternduCode** [comment]
And yes WIN+L doesnt work for some reason but i dont think this is the fault of messageclient, but from the underling lib.

**Comment by SternduCode** [comment]
Windows curl removes " and keeps the '.

For windows curl youd need to write the post data like this:
"{\\"type\\":\\"message\\",\\"payload\\":\\"Hello, this is a test message!\\"}"

**Comment by slimline33** [comment]
@SternduCode thanks! this work!

To lock Windows, I've now set up the following workaround: a shortcut on the desktop containing the command 'C:\Windows\System32\rundll32.exe user32.dll, LockWorkStation,' with an alternative key combination added.
